//
//  ResultReason.hpp
//  CoreML
//
//  Created by Jeff Kilpatrick on 12/16/19.
//  Copyright © 2019 Apple Inc. All rights reserved.
//

#pragma once

namespace CoreML {

/**
 Super specific reasons for non-good Results.
 */
enum class ResultReason {
    UNKNOWN,

    // -----------------------------------------
    // Model validation
    MODEL_INVALID_INPUT_TYPE,
    MODEL_INVALID_OUTPUT_TYPE,

    // -----------------------------------------
    // Program validation
    BLOCK_ARG_NAME_EMPTY,
    BLOCK_ARG_VALUE_UNDEFINED,
    BLOCK_OUTPUT_NAME_EMPTY,
    BLOCK_OUTPUT_VALUE_UNDEFINED,
    BLOCK_PARAM_NAME_EMPTY,

    FUNCTION_NAME_EMPTY,
    FUNCTION_PARAM_NAME_EMPTY,
    FUNCTION_PARAM_TYPE_NULL,
    FUNCTION_BLOCK_MISMATCHED_RETURN_COUNT,
    FUNCTION_BLOCK_MISMATCHED_RETURN_TYPE,

    MODEL_MAIN_INPUT_MISMATCHED_RANK,
    MODEL_MAIN_MISMATCHED_INPUT_COUNT,
    MODEL_MAIN_MISMATCHED_INPUT_SHAPE,
    MODEL_MAIN_MISMATCHED_INPUT_TYPE,
    MODEL_MAIN_MISMATCHED_OUTPUT_COUNT,
    MODEL_MAIN_MISMATCHED_OUTPUT_SHAPE,
    MODEL_MAIN_MISMATCHED_OUTPUT_TYPE,
    MODEL_MAIN_MISSING_INPUT_OUTPUT,
    MODEL_MAIN_NON_TENSOR_INPUT_OUTPUT,
    MODEL_MAIN_OUTPUT_MISMATCHED_RANK,

    OP_ARG_NAME_EMPTY,
    OP_ARG_VALUE_UNDEFINED,
    OP_ATTRIBUTE_NAME_EMPTY,
    OP_ATTRIBUTE_VALUE_UNDEFINED,
    OP_NAME_EMPTY,
    OP_OUTPUT_NAME_EMPTY,
    OP_PARAM_NAME_EMPTY,

    PARAMETER_NAME_EMPTY,
    PARAMETER_VALUE_UNDEFINED,

    PROGRAM_MISSING_MAIN_FUNCTION,
    PROGRAM_NULL,
    PROGRAM_PARSE_THREW,
};

}
