//
//  ResultReason.hpp
//  CoreML
//
//  Created by Jeff Kilpatrick on 12/16/19.
//  Copyright © 2019 Apple Inc. All rights reserved.
//

#pragma once

namespace CoreML {

/**
 Super specific reasons for non-good Results.
 */
enum class ResultReason {
    UNKNOWN,

    // -----------------------------------------
    // Model validation
    MODEL_INVALID_INPUT_TYPE,
    MODEL_INVALID_OUTPUT_TYPE,

    // -----------------------------------------
    // Program validation
    BLOCK_ARG_NAME_EMPTY,
    BLOCK_ARG_VALUE_UNDEFINED,
    BLOCK_OUTPUT_NAME_EMPTY,
    BLOCK_OUTPUT_VALUE_UNDEFINED,
    BLOCK_PARAM_NAME_EMPTY,
    BLOCK_PARAM_NAME_SHADOWS,

    FUNCTION_BLOCK_MISMATCHED_RETURN_COUNT,
    FUNCTION_BLOCK_MISMATCHED_RETURN_TYPE,
    FUNCTION_NAME_EMPTY,
    FUNCTION_PARAM_NAME_EMPTY,
    FUNCTION_PARAM_NAME_SHADOWS,
    FUNCTION_PARAM_TYPE_NULL,

    MODEL_MAIN_BAD_IMAGE_INPUT_SIZE,
    MODEL_MAIN_BAD_IMAGE_INPUT_TYPE,
    MODEL_MAIN_BAD_IMAGE_OUTPUT_SIZE,
    MODEL_MAIN_BAD_IMAGE_OUTPUT_TYPE,
    MODEL_MAIN_INPUT_MISMATCHED_RANK,
    MODEL_MAIN_MISMATCHED_INPUT_COUNT,
    MODEL_MAIN_MISMATCHED_INPUT_SHAPE,
    MODEL_MAIN_MISMATCHED_INPUT_TYPE,
    MODEL_MAIN_MISMATCHED_OUTPUT_COUNT,
    MODEL_MAIN_MISMATCHED_OUTPUT_SHAPE,
    MODEL_MAIN_MISMATCHED_OUTPUT_TYPE,
    MODEL_MAIN_MISSING_INPUT_OUTPUT,
    MODEL_MAIN_INVALID_INPUT_OUTPUT_TYPE,
    MODEL_MAIN_OUTPUT_MISMATCHED_RANK,

    OP_ARG_COUNT_MISMATCH,
    OP_ARG_NAME_EMPTY,
    OP_ARG_OUTPUT_CIRCULAR_DEFINITION,
    OP_ARG_TYPE_MISMATCH,
    OP_ARG_VALUE_UNDEFINED,
    OP_ATTRIBUTE_NAME_EMPTY,
    OP_ATTRIBUTE_VALUE_UNDEFINED,
    OP_INVALID_IN_CONTEXT,
    OP_MISMATCHED_PARAM_COUNT,
    OP_MISMATCHED_OUTPUT_COUNT,
    OP_NAME_EMPTY,
    OP_OUTPUT_NAME_EMPTY,
    OP_OUTPUT_NAME_SHADOWS,
    OP_OUTPUT_TYPE_INVALID,
    OP_PARAM_INVALID,
    OP_PARAM_NAME_EMPTY,
    OP_REQUIRED_ARG_NOT_FOUND,

    PARAMETER_NAME_EMPTY,
    PARAMETER_VALUE_UNDEFINED,

    PROGRAM_MISSING_MAIN_FUNCTION,
    PROGRAM_NULL,
    PROGRAM_PARSE_THREW,
};

}
