# A CentOS 6 based image that is used for gitlab based ci infrastructure
# (Using an older distribution like CentOS 6 allows for maximum binary compatibility)
# Source for this image is https://github.com/apple/turicreate/blob/master/scripts/Dockerfile-CentOS-6
# This image should be published to registry.gitlab.com/zach_nation/coremltools/build-image-centos-6:1.0.0
FROM registry.gitlab.com/zach_nation/turicreate/build-image-centos-6:1.0.6

# Install zsh
RUN yum install -y zsh

# Install miniconda
RUN mkdir -p /src
WORKDIR /src

RUN curl -O https://repo.anaconda.com/miniconda/Miniconda3-py38_4.8.2-Linux-x86_64.sh
RUN bash Miniconda3-py38_4.8.2-Linux-x86_64.sh -b -p $HOME/miniconda3
# hook conda into both bash and zsh
RUN eval "$($HOME/miniconda3/bin/conda shell.bash hook)" && conda init bash && conda config --set auto_activate_base false
RUN zsh -c 'eval "$($HOME/miniconda3/bin/conda shell.zsh hook)" && conda init zsh && conda config --set auto_activate_base false'

# Clean up now-unnecessary paths in image
RUN rm -rf /src

# start at gitlab build dir
WORKDIR /build/