# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ArrayFeatureExtractor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1b\x41rrayFeatureExtractor.proto\x12\x14\x43oreML.Specification\"-\n\x15\x41rrayFeatureExtractor\x12\x14\n\x0c\x65xtractIndex\x18\x01 \x03(\x04\x42\x02H\x03\x62\x06proto3')



_ARRAYFEATUREEXTRACTOR = DESCRIPTOR.message_types_by_name['ArrayFeatureExtractor']
ArrayFeatureExtractor = _reflection.GeneratedProtocolMessageType('ArrayFeatureExtractor', (_message.Message,), {
  'DESCRIPTOR' : _ARRAYFEATUREEXTRACTOR,
  '__module__' : 'ArrayFeatureExtractor_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.ArrayFeatureExtractor)
  })
_sym_db.RegisterMessage(ArrayFeatureExtractor)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _ARRAYFEATUREEXTRACTOR._serialized_start=53
  _ARRAYFEATUREEXTRACTOR._serialized_end=98
# @@protoc_insertion_point(module_scope)
