# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: AudioFeaturePrint.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17\x41udioFeaturePrint.proto\x12!CoreML.Specification.CoreMLModels\"\x9d\x02\n\x11\x41udioFeaturePrint\x12K\n\x05sound\x18\x14 \x01(\x0b\x32:.CoreML.Specification.CoreMLModels.AudioFeaturePrint.SoundH\x00\x1a\xa1\x01\n\x05Sound\x12X\n\x07version\x18\x01 \x01(\x0e\x32G.CoreML.Specification.CoreMLModels.AudioFeaturePrint.Sound.SoundVersion\">\n\x0cSoundVersion\x12\x19\n\x15SOUND_VERSION_INVALID\x10\x00\x12\x13\n\x0fSOUND_VERSION_1\x10\x01\x42\x17\n\x15\x41udioFeaturePrintTypeB\x02H\x03\x62\x06proto3')



_AUDIOFEATUREPRINT = DESCRIPTOR.message_types_by_name['AudioFeaturePrint']
_AUDIOFEATUREPRINT_SOUND = _AUDIOFEATUREPRINT.nested_types_by_name['Sound']
_AUDIOFEATUREPRINT_SOUND_SOUNDVERSION = _AUDIOFEATUREPRINT_SOUND.enum_types_by_name['SoundVersion']
AudioFeaturePrint = _reflection.GeneratedProtocolMessageType('AudioFeaturePrint', (_message.Message,), {

  'Sound' : _reflection.GeneratedProtocolMessageType('Sound', (_message.Message,), {
    'DESCRIPTOR' : _AUDIOFEATUREPRINT_SOUND,
    '__module__' : 'AudioFeaturePrint_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.CoreMLModels.AudioFeaturePrint.Sound)
    })
  ,
  'DESCRIPTOR' : _AUDIOFEATUREPRINT,
  '__module__' : 'AudioFeaturePrint_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.CoreMLModels.AudioFeaturePrint)
  })
_sym_db.RegisterMessage(AudioFeaturePrint)
_sym_db.RegisterMessage(AudioFeaturePrint.Sound)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _AUDIOFEATUREPRINT._serialized_start=63
  _AUDIOFEATUREPRINT._serialized_end=348
  _AUDIOFEATUREPRINT_SOUND._serialized_start=162
  _AUDIOFEATUREPRINT_SOUND._serialized_end=323
  _AUDIOFEATUREPRINT_SOUND_SOUNDVERSION._serialized_start=261
  _AUDIOFEATUREPRINT_SOUND_SOUNDVERSION._serialized_end=323
# @@protoc_insertion_point(module_scope)
