# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: BayesianProbitRegressor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1d\x42\x61yesianProbitRegressor.proto\x12\x14\x43oreML.Specification\"\xa0\x06\n\x17\x42\x61yesianProbitRegressor\x12\x18\n\x10numberOfFeatures\x18\x01 \x01(\r\x12\x44\n\x04\x62ias\x18\x02 \x01(\x0b\x32\x36.CoreML.Specification.BayesianProbitRegressor.Gaussian\x12M\n\x08\x66\x65\x61tures\x18\x03 \x03(\x0b\x32;.CoreML.Specification.BayesianProbitRegressor.FeatureWeight\x12\"\n\x1aregressionInputFeatureName\x18\n \x01(\t\x12 \n\x18optimismInputFeatureName\x18\x0b \x01(\t\x12%\n\x1dsamplingScaleInputFeatureName\x18\x0c \x01(\t\x12*\n\"samplingTruncationInputFeatureName\x18\r \x01(\t\x12\x1d\n\x15meanOutputFeatureName\x18\x14 \x01(\t\x12!\n\x19varianceOutputFeatureName\x18\x15 \x01(\t\x12/\n\'pessimisticProbabilityOutputFeatureName\x18\x16 \x01(\t\x12+\n#sampledProbabilityOutputFeatureName\x18\x17 \x01(\t\x1a+\n\x08Gaussian\x12\x0c\n\x04mean\x18\x01 \x01(\x01\x12\x11\n\tprecision\x18\x02 \x01(\x01\x1ay\n\x12\x46\x65\x61tureValueWeight\x12\x14\n\x0c\x66\x65\x61tureValue\x18\x01 \x01(\r\x12M\n\rfeatureWeight\x18\x02 \x01(\x0b\x32\x36.CoreML.Specification.BayesianProbitRegressor.Gaussian\x1au\n\rFeatureWeight\x12\x11\n\tfeatureId\x18\x01 \x01(\r\x12Q\n\x07weights\x18\x02 \x03(\x0b\x32@.CoreML.Specification.BayesianProbitRegressor.FeatureValueWeightB\x02H\x03\x62\x06proto3')



_BAYESIANPROBITREGRESSOR = DESCRIPTOR.message_types_by_name['BayesianProbitRegressor']
_BAYESIANPROBITREGRESSOR_GAUSSIAN = _BAYESIANPROBITREGRESSOR.nested_types_by_name['Gaussian']
_BAYESIANPROBITREGRESSOR_FEATUREVALUEWEIGHT = _BAYESIANPROBITREGRESSOR.nested_types_by_name['FeatureValueWeight']
_BAYESIANPROBITREGRESSOR_FEATUREWEIGHT = _BAYESIANPROBITREGRESSOR.nested_types_by_name['FeatureWeight']
BayesianProbitRegressor = _reflection.GeneratedProtocolMessageType('BayesianProbitRegressor', (_message.Message,), {

  'Gaussian' : _reflection.GeneratedProtocolMessageType('Gaussian', (_message.Message,), {
    'DESCRIPTOR' : _BAYESIANPROBITREGRESSOR_GAUSSIAN,
    '__module__' : 'BayesianProbitRegressor_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.BayesianProbitRegressor.Gaussian)
    })
  ,

  'FeatureValueWeight' : _reflection.GeneratedProtocolMessageType('FeatureValueWeight', (_message.Message,), {
    'DESCRIPTOR' : _BAYESIANPROBITREGRESSOR_FEATUREVALUEWEIGHT,
    '__module__' : 'BayesianProbitRegressor_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.BayesianProbitRegressor.FeatureValueWeight)
    })
  ,

  'FeatureWeight' : _reflection.GeneratedProtocolMessageType('FeatureWeight', (_message.Message,), {
    'DESCRIPTOR' : _BAYESIANPROBITREGRESSOR_FEATUREWEIGHT,
    '__module__' : 'BayesianProbitRegressor_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.BayesianProbitRegressor.FeatureWeight)
    })
  ,
  'DESCRIPTOR' : _BAYESIANPROBITREGRESSOR,
  '__module__' : 'BayesianProbitRegressor_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.BayesianProbitRegressor)
  })
_sym_db.RegisterMessage(BayesianProbitRegressor)
_sym_db.RegisterMessage(BayesianProbitRegressor.Gaussian)
_sym_db.RegisterMessage(BayesianProbitRegressor.FeatureValueWeight)
_sym_db.RegisterMessage(BayesianProbitRegressor.FeatureWeight)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _BAYESIANPROBITREGRESSOR._serialized_start=56
  _BAYESIANPROBITREGRESSOR._serialized_end=856
  _BAYESIANPROBITREGRESSOR_GAUSSIAN._serialized_start=571
  _BAYESIANPROBITREGRESSOR_GAUSSIAN._serialized_end=614
  _BAYESIANPROBITREGRESSOR_FEATUREVALUEWEIGHT._serialized_start=616
  _BAYESIANPROBITREGRESSOR_FEATUREVALUEWEIGHT._serialized_end=737
  _BAYESIANPROBITREGRESSOR_FEATUREWEIGHT._serialized_start=739
  _BAYESIANPROBITREGRESSOR_FEATUREWEIGHT._serialized_end=856
# @@protoc_insertion_point(module_scope)
