# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ClassConfidenceThresholding.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import DataStructures_pb2 as DataStructures__pb2
try:
  FeatureTypes__pb2 = DataStructures__pb2.FeatureTypes__pb2
except AttributeError:
  FeatureTypes__pb2 = DataStructures__pb2.FeatureTypes_pb2

from .DataStructures_pb2 import *

DESCRIPTOR = _descriptor.FileDescriptor(
  name='ClassConfidenceThresholding.proto',
  package='CoreML.Specification',
  syntax='proto3',
  serialized_pb=_b('\n!ClassConfidenceThresholding.proto\x12\x14\x43oreML.Specification\x1a\x14\x44\x61taStructures.proto\"h\n\x1b\x43lassConfidenceThresholding\x12I\n\x15precisionRecallCurves\x18\x64 \x03(\x0b\x32*.CoreML.Specification.PrecisionRecallCurveB\x02H\x03P\x00\x62\x06proto3')
  ,
  dependencies=[DataStructures__pb2.DESCRIPTOR,],
  public_dependencies=[DataStructures__pb2.DESCRIPTOR,])




_CLASSCONFIDENCETHRESHOLDING = _descriptor.Descriptor(
  name='ClassConfidenceThresholding',
  full_name='CoreML.Specification.ClassConfidenceThresholding',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='precisionRecallCurves', full_name='CoreML.Specification.ClassConfidenceThresholding.precisionRecallCurves', index=0,
      number=100, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=81,
  serialized_end=185,
)

_CLASSCONFIDENCETHRESHOLDING.fields_by_name['precisionRecallCurves'].message_type = DataStructures__pb2._PRECISIONRECALLCURVE
DESCRIPTOR.message_types_by_name['ClassConfidenceThresholding'] = _CLASSCONFIDENCETHRESHOLDING
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

ClassConfidenceThresholding = _reflection.GeneratedProtocolMessageType('ClassConfidenceThresholding', (_message.Message,), dict(
  DESCRIPTOR = _CLASSCONFIDENCETHRESHOLDING,
  __module__ = 'ClassConfidenceThresholding_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.ClassConfidenceThresholding)
  ))
_sym_db.RegisterMessage(ClassConfidenceThresholding)


DESCRIPTOR.has_options = True
DESCRIPTOR._options = _descriptor._ParseOptions(descriptor_pb2.FileOptions(), _b('H\003'))
# @@protoc_insertion_point(module_scope)
