# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: DataStructures.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import FeatureTypes_pb2 as FeatureTypes__pb2

from .FeatureTypes_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x14\x44\x61taStructures.proto\x12\x14\x43oreML.Specification\x1a\x12\x46\x65\x61tureTypes.proto\"|\n\x10StringToInt64Map\x12<\n\x03map\x18\x01 \x03(\x0b\x32/.CoreML.Specification.StringToInt64Map.MapEntry\x1a*\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x03:\x02\x38\x01\"|\n\x10Int64ToStringMap\x12<\n\x03map\x18\x01 \x03(\x0b\x32/.CoreML.Specification.Int64ToStringMap.MapEntry\x1a*\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"~\n\x11StringToDoubleMap\x12=\n\x03map\x18\x01 \x03(\x0b\x32\x30.CoreML.Specification.StringToDoubleMap.MapEntry\x1a*\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"|\n\x10Int64ToDoubleMap\x12<\n\x03map\x18\x01 \x03(\x0b\x32/.CoreML.Specification.Int64ToDoubleMap.MapEntry\x1a*\n\x08MapEntry\x12\x0b\n\x03key\x18\x01 \x01(\x03\x12\r\n\x05value\x18\x02 \x01(\x01:\x02\x38\x01\"\x1e\n\x0cStringVector\x12\x0e\n\x06vector\x18\x01 \x03(\t\"\x1d\n\x0bInt64Vector\x12\x0e\n\x06vector\x18\x01 \x03(\x03\"\x1d\n\x0b\x46loatVector\x12\x0e\n\x06vector\x18\x01 \x03(\x02\"\x1e\n\x0c\x44oubleVector\x12\x0e\n\x06vector\x18\x01 \x03(\x01\"0\n\nInt64Range\x12\x10\n\x08minValue\x18\x01 \x01(\x03\x12\x10\n\x08maxValue\x18\x02 \x01(\x03\"\x1a\n\x08Int64Set\x12\x0e\n\x06values\x18\x01 \x03(\x03\"1\n\x0b\x44oubleRange\x12\x10\n\x08minValue\x18\x01 \x01(\x01\x12\x10\n\x08maxValue\x18\x02 \x01(\x01\"\x9c\x02\n\x14PrecisionRecallCurve\x12:\n\x0fprecisionValues\x18\x01 \x01(\x0b\x32!.CoreML.Specification.FloatVector\x12H\n\x1dprecisionConfidenceThresholds\x18\x02 \x01(\x0b\x32!.CoreML.Specification.FloatVector\x12\x37\n\x0crecallValues\x18\x03 \x01(\x0b\x32!.CoreML.Specification.FloatVector\x12\x45\n\x1arecallConfidenceThresholds\x18\x04 \x01(\x0b\x32!.CoreML.Specification.FloatVectorB\x02H\x03P\x00\x62\x06proto3')



_STRINGTOINT64MAP = DESCRIPTOR.message_types_by_name['StringToInt64Map']
_STRINGTOINT64MAP_MAPENTRY = _STRINGTOINT64MAP.nested_types_by_name['MapEntry']
_INT64TOSTRINGMAP = DESCRIPTOR.message_types_by_name['Int64ToStringMap']
_INT64TOSTRINGMAP_MAPENTRY = _INT64TOSTRINGMAP.nested_types_by_name['MapEntry']
_STRINGTODOUBLEMAP = DESCRIPTOR.message_types_by_name['StringToDoubleMap']
_STRINGTODOUBLEMAP_MAPENTRY = _STRINGTODOUBLEMAP.nested_types_by_name['MapEntry']
_INT64TODOUBLEMAP = DESCRIPTOR.message_types_by_name['Int64ToDoubleMap']
_INT64TODOUBLEMAP_MAPENTRY = _INT64TODOUBLEMAP.nested_types_by_name['MapEntry']
_STRINGVECTOR = DESCRIPTOR.message_types_by_name['StringVector']
_INT64VECTOR = DESCRIPTOR.message_types_by_name['Int64Vector']
_FLOATVECTOR = DESCRIPTOR.message_types_by_name['FloatVector']
_DOUBLEVECTOR = DESCRIPTOR.message_types_by_name['DoubleVector']
_INT64RANGE = DESCRIPTOR.message_types_by_name['Int64Range']
_INT64SET = DESCRIPTOR.message_types_by_name['Int64Set']
_DOUBLERANGE = DESCRIPTOR.message_types_by_name['DoubleRange']
_PRECISIONRECALLCURVE = DESCRIPTOR.message_types_by_name['PrecisionRecallCurve']
StringToInt64Map = _reflection.GeneratedProtocolMessageType('StringToInt64Map', (_message.Message,), {

  'MapEntry' : _reflection.GeneratedProtocolMessageType('MapEntry', (_message.Message,), {
    'DESCRIPTOR' : _STRINGTOINT64MAP_MAPENTRY,
    '__module__' : 'DataStructures_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.StringToInt64Map.MapEntry)
    })
  ,
  'DESCRIPTOR' : _STRINGTOINT64MAP,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.StringToInt64Map)
  })
_sym_db.RegisterMessage(StringToInt64Map)
_sym_db.RegisterMessage(StringToInt64Map.MapEntry)

Int64ToStringMap = _reflection.GeneratedProtocolMessageType('Int64ToStringMap', (_message.Message,), {

  'MapEntry' : _reflection.GeneratedProtocolMessageType('MapEntry', (_message.Message,), {
    'DESCRIPTOR' : _INT64TOSTRINGMAP_MAPENTRY,
    '__module__' : 'DataStructures_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.Int64ToStringMap.MapEntry)
    })
  ,
  'DESCRIPTOR' : _INT64TOSTRINGMAP,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.Int64ToStringMap)
  })
_sym_db.RegisterMessage(Int64ToStringMap)
_sym_db.RegisterMessage(Int64ToStringMap.MapEntry)

StringToDoubleMap = _reflection.GeneratedProtocolMessageType('StringToDoubleMap', (_message.Message,), {

  'MapEntry' : _reflection.GeneratedProtocolMessageType('MapEntry', (_message.Message,), {
    'DESCRIPTOR' : _STRINGTODOUBLEMAP_MAPENTRY,
    '__module__' : 'DataStructures_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.StringToDoubleMap.MapEntry)
    })
  ,
  'DESCRIPTOR' : _STRINGTODOUBLEMAP,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.StringToDoubleMap)
  })
_sym_db.RegisterMessage(StringToDoubleMap)
_sym_db.RegisterMessage(StringToDoubleMap.MapEntry)

Int64ToDoubleMap = _reflection.GeneratedProtocolMessageType('Int64ToDoubleMap', (_message.Message,), {

  'MapEntry' : _reflection.GeneratedProtocolMessageType('MapEntry', (_message.Message,), {
    'DESCRIPTOR' : _INT64TODOUBLEMAP_MAPENTRY,
    '__module__' : 'DataStructures_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.Int64ToDoubleMap.MapEntry)
    })
  ,
  'DESCRIPTOR' : _INT64TODOUBLEMAP,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.Int64ToDoubleMap)
  })
_sym_db.RegisterMessage(Int64ToDoubleMap)
_sym_db.RegisterMessage(Int64ToDoubleMap.MapEntry)

StringVector = _reflection.GeneratedProtocolMessageType('StringVector', (_message.Message,), {
  'DESCRIPTOR' : _STRINGVECTOR,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.StringVector)
  })
_sym_db.RegisterMessage(StringVector)

Int64Vector = _reflection.GeneratedProtocolMessageType('Int64Vector', (_message.Message,), {
  'DESCRIPTOR' : _INT64VECTOR,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.Int64Vector)
  })
_sym_db.RegisterMessage(Int64Vector)

FloatVector = _reflection.GeneratedProtocolMessageType('FloatVector', (_message.Message,), {
  'DESCRIPTOR' : _FLOATVECTOR,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.FloatVector)
  })
_sym_db.RegisterMessage(FloatVector)

DoubleVector = _reflection.GeneratedProtocolMessageType('DoubleVector', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLEVECTOR,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.DoubleVector)
  })
_sym_db.RegisterMessage(DoubleVector)

Int64Range = _reflection.GeneratedProtocolMessageType('Int64Range', (_message.Message,), {
  'DESCRIPTOR' : _INT64RANGE,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.Int64Range)
  })
_sym_db.RegisterMessage(Int64Range)

Int64Set = _reflection.GeneratedProtocolMessageType('Int64Set', (_message.Message,), {
  'DESCRIPTOR' : _INT64SET,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.Int64Set)
  })
_sym_db.RegisterMessage(Int64Set)

DoubleRange = _reflection.GeneratedProtocolMessageType('DoubleRange', (_message.Message,), {
  'DESCRIPTOR' : _DOUBLERANGE,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.DoubleRange)
  })
_sym_db.RegisterMessage(DoubleRange)

PrecisionRecallCurve = _reflection.GeneratedProtocolMessageType('PrecisionRecallCurve', (_message.Message,), {
  'DESCRIPTOR' : _PRECISIONRECALLCURVE,
  '__module__' : 'DataStructures_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.PrecisionRecallCurve)
  })
_sym_db.RegisterMessage(PrecisionRecallCurve)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _STRINGTOINT64MAP_MAPENTRY._options = None
  _STRINGTOINT64MAP_MAPENTRY._serialized_options = b'8\001'
  _INT64TOSTRINGMAP_MAPENTRY._options = None
  _INT64TOSTRINGMAP_MAPENTRY._serialized_options = b'8\001'
  _STRINGTODOUBLEMAP_MAPENTRY._options = None
  _STRINGTODOUBLEMAP_MAPENTRY._serialized_options = b'8\001'
  _INT64TODOUBLEMAP_MAPENTRY._options = None
  _INT64TODOUBLEMAP_MAPENTRY._serialized_options = b'8\001'
  _STRINGTOINT64MAP._serialized_start=66
  _STRINGTOINT64MAP._serialized_end=190
  _STRINGTOINT64MAP_MAPENTRY._serialized_start=148
  _STRINGTOINT64MAP_MAPENTRY._serialized_end=190
  _INT64TOSTRINGMAP._serialized_start=192
  _INT64TOSTRINGMAP._serialized_end=316
  _INT64TOSTRINGMAP_MAPENTRY._serialized_start=274
  _INT64TOSTRINGMAP_MAPENTRY._serialized_end=316
  _STRINGTODOUBLEMAP._serialized_start=318
  _STRINGTODOUBLEMAP._serialized_end=444
  _STRINGTODOUBLEMAP_MAPENTRY._serialized_start=402
  _STRINGTODOUBLEMAP_MAPENTRY._serialized_end=444
  _INT64TODOUBLEMAP._serialized_start=446
  _INT64TODOUBLEMAP._serialized_end=570
  _INT64TODOUBLEMAP_MAPENTRY._serialized_start=528
  _INT64TODOUBLEMAP_MAPENTRY._serialized_end=570
  _STRINGVECTOR._serialized_start=572
  _STRINGVECTOR._serialized_end=602
  _INT64VECTOR._serialized_start=604
  _INT64VECTOR._serialized_end=633
  _FLOATVECTOR._serialized_start=635
  _FLOATVECTOR._serialized_end=664
  _DOUBLEVECTOR._serialized_start=666
  _DOUBLEVECTOR._serialized_end=696
  _INT64RANGE._serialized_start=698
  _INT64RANGE._serialized_end=746
  _INT64SET._serialized_start=748
  _INT64SET._serialized_end=774
  _DOUBLERANGE._serialized_start=776
  _DOUBLERANGE._serialized_end=825
  _PRECISIONRECALLCURVE._serialized_start=828
  _PRECISIONRECALLCURVE._serialized_end=1112
# @@protoc_insertion_point(module_scope)
