# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GLMClassifier.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import DataStructures_pb2 as DataStructures__pb2
try:
  FeatureTypes__pb2 = DataStructures__pb2.FeatureTypes__pb2
except AttributeError:
  FeatureTypes__pb2 = DataStructures__pb2.FeatureTypes_pb2

from .DataStructures_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13GLMClassifier.proto\x12\x14\x43oreML.Specification\x1a\x14\x44\x61taStructures.proto\"\x9c\x04\n\rGLMClassifier\x12@\n\x07weights\x18\x01 \x03(\x0b\x32/.CoreML.Specification.GLMClassifier.DoubleArray\x12\x0e\n\x06offset\x18\x02 \x03(\x01\x12\\\n\x17postEvaluationTransform\x18\x03 \x01(\x0e\x32;.CoreML.Specification.GLMClassifier.PostEvaluationTransform\x12H\n\rclassEncoding\x18\x04 \x01(\x0e\x32\x31.CoreML.Specification.GLMClassifier.ClassEncoding\x12?\n\x11stringClassLabels\x18\x64 \x01(\x0b\x32\".CoreML.Specification.StringVectorH\x00\x12=\n\x10int64ClassLabels\x18\x65 \x01(\x0b\x32!.CoreML.Specification.Int64VectorH\x00\x1a\x1c\n\x0b\x44oubleArray\x12\r\n\x05value\x18\x01 \x03(\x01\"0\n\x17PostEvaluationTransform\x12\t\n\x05Logit\x10\x00\x12\n\n\x06Probit\x10\x01\"2\n\rClassEncoding\x12\x12\n\x0eReferenceClass\x10\x00\x12\r\n\tOneVsRest\x10\x01\x42\r\n\x0b\x43lassLabelsB\x02H\x03P\x00\x62\x06proto3')



_GLMCLASSIFIER = DESCRIPTOR.message_types_by_name['GLMClassifier']
_GLMCLASSIFIER_DOUBLEARRAY = _GLMCLASSIFIER.nested_types_by_name['DoubleArray']
_GLMCLASSIFIER_POSTEVALUATIONTRANSFORM = _GLMCLASSIFIER.enum_types_by_name['PostEvaluationTransform']
_GLMCLASSIFIER_CLASSENCODING = _GLMCLASSIFIER.enum_types_by_name['ClassEncoding']
GLMClassifier = _reflection.GeneratedProtocolMessageType('GLMClassifier', (_message.Message,), {

  'DoubleArray' : _reflection.GeneratedProtocolMessageType('DoubleArray', (_message.Message,), {
    'DESCRIPTOR' : _GLMCLASSIFIER_DOUBLEARRAY,
    '__module__' : 'GLMClassifier_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.GLMClassifier.DoubleArray)
    })
  ,
  'DESCRIPTOR' : _GLMCLASSIFIER,
  '__module__' : 'GLMClassifier_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.GLMClassifier)
  })
_sym_db.RegisterMessage(GLMClassifier)
_sym_db.RegisterMessage(GLMClassifier.DoubleArray)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _GLMCLASSIFIER._serialized_start=68
  _GLMCLASSIFIER._serialized_end=608
  _GLMCLASSIFIER_DOUBLEARRAY._serialized_start=463
  _GLMCLASSIFIER_DOUBLEARRAY._serialized_end=491
  _GLMCLASSIFIER_POSTEVALUATIONTRANSFORM._serialized_start=493
  _GLMCLASSIFIER_POSTEVALUATIONTRANSFORM._serialized_end=541
  _GLMCLASSIFIER_CLASSENCODING._serialized_start=543
  _GLMCLASSIFIER_CLASSENCODING._serialized_end=593
# @@protoc_insertion_point(module_scope)
