# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: GLMRegressor.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12GLMRegressor.proto\x12\x14\x43oreML.Specification\"\x9d\x02\n\x0cGLMRegressor\x12?\n\x07weights\x18\x01 \x03(\x0b\x32..CoreML.Specification.GLMRegressor.DoubleArray\x12\x0e\n\x06offset\x18\x02 \x03(\x01\x12[\n\x17postEvaluationTransform\x18\x03 \x01(\x0e\x32:.CoreML.Specification.GLMRegressor.PostEvaluationTransform\x1a\x1c\n\x0b\x44oubleArray\x12\r\n\x05value\x18\x01 \x03(\x01\"A\n\x17PostEvaluationTransform\x12\x0f\n\x0bNoTransform\x10\x00\x12\t\n\x05Logit\x10\x01\x12\n\n\x06Probit\x10\x02\x42\x02H\x03\x62\x06proto3')



_GLMREGRESSOR = DESCRIPTOR.message_types_by_name['GLMRegressor']
_GLMREGRESSOR_DOUBLEARRAY = _GLMREGRESSOR.nested_types_by_name['DoubleArray']
_GLMREGRESSOR_POSTEVALUATIONTRANSFORM = _GLMREGRESSOR.enum_types_by_name['PostEvaluationTransform']
GLMRegressor = _reflection.GeneratedProtocolMessageType('GLMRegressor', (_message.Message,), {

  'DoubleArray' : _reflection.GeneratedProtocolMessageType('DoubleArray', (_message.Message,), {
    'DESCRIPTOR' : _GLMREGRESSOR_DOUBLEARRAY,
    '__module__' : 'GLMRegressor_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.GLMRegressor.DoubleArray)
    })
  ,
  'DESCRIPTOR' : _GLMREGRESSOR,
  '__module__' : 'GLMRegressor_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.GLMRegressor)
  })
_sym_db.RegisterMessage(GLMRegressor)
_sym_db.RegisterMessage(GLMRegressor.DoubleArray)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _GLMREGRESSOR._serialized_start=45
  _GLMREGRESSOR._serialized_end=330
  _GLMREGRESSOR_DOUBLEARRAY._serialized_start=235
  _GLMREGRESSOR_DOUBLEARRAY._serialized_end=263
  _GLMREGRESSOR_POSTEVALUATIONTRANSFORM._serialized_start=265
  _GLMREGRESSOR_POSTEVALUATIONTRANSFORM._serialized_end=330
# @@protoc_insertion_point(module_scope)
