# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ItemSimilarityRecommender.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import DataStructures_pb2 as DataStructures__pb2
try:
  FeatureTypes__pb2 = DataStructures__pb2.FeatureTypes__pb2
except AttributeError:
  FeatureTypes__pb2 = DataStructures__pb2.FeatureTypes_pb2

from .DataStructures_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1fItemSimilarityRecommender.proto\x12\x14\x43oreML.Specification\x1a\x14\x44\x61taStructures.proto\"\xb2\x05\n\x19ItemSimilarityRecommender\x12Z\n\x14itemItemSimilarities\x18\x01 \x03(\x0b\x32<.CoreML.Specification.ItemSimilarityRecommender.SimilarItems\x12\x39\n\ritemStringIds\x18\x02 \x01(\x0b\x32\".CoreML.Specification.StringVector\x12\x37\n\x0citemInt64Ids\x18\x03 \x01(\x0b\x32!.CoreML.Specification.Int64Vector\x12\x1c\n\x14itemInputFeatureName\x18\n \x01(\t\x12*\n\"numRecommendationsInputFeatureName\x18\x0b \x01(\t\x12\'\n\x1fitemRestrictionInputFeatureName\x18\x0c \x01(\t\x12%\n\x1ditemExclusionInputFeatureName\x18\r \x01(\t\x12,\n$recommendedItemListOutputFeatureName\x18\x14 \x01(\t\x12-\n%recommendedItemScoreOutputFeatureName\x18\x15 \x01(\t\x1a\x38\n\rConnectedItem\x12\x0e\n\x06itemId\x18\x01 \x01(\x04\x12\x17\n\x0fsimilarityScore\x18\x02 \x01(\x01\x1a\x93\x01\n\x0cSimilarItems\x12\x0e\n\x06itemId\x18\x01 \x01(\x04\x12V\n\x0fsimilarItemList\x18\x02 \x03(\x0b\x32=.CoreML.Specification.ItemSimilarityRecommender.ConnectedItem\x12\x1b\n\x13itemScoreAdjustment\x18\x03 \x01(\x01\x42\x02H\x03P\x00\x62\x06proto3')



_ITEMSIMILARITYRECOMMENDER = DESCRIPTOR.message_types_by_name['ItemSimilarityRecommender']
_ITEMSIMILARITYRECOMMENDER_CONNECTEDITEM = _ITEMSIMILARITYRECOMMENDER.nested_types_by_name['ConnectedItem']
_ITEMSIMILARITYRECOMMENDER_SIMILARITEMS = _ITEMSIMILARITYRECOMMENDER.nested_types_by_name['SimilarItems']
ItemSimilarityRecommender = _reflection.GeneratedProtocolMessageType('ItemSimilarityRecommender', (_message.Message,), {

  'ConnectedItem' : _reflection.GeneratedProtocolMessageType('ConnectedItem', (_message.Message,), {
    'DESCRIPTOR' : _ITEMSIMILARITYRECOMMENDER_CONNECTEDITEM,
    '__module__' : 'ItemSimilarityRecommender_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.ItemSimilarityRecommender.ConnectedItem)
    })
  ,

  'SimilarItems' : _reflection.GeneratedProtocolMessageType('SimilarItems', (_message.Message,), {
    'DESCRIPTOR' : _ITEMSIMILARITYRECOMMENDER_SIMILARITEMS,
    '__module__' : 'ItemSimilarityRecommender_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.ItemSimilarityRecommender.SimilarItems)
    })
  ,
  'DESCRIPTOR' : _ITEMSIMILARITYRECOMMENDER,
  '__module__' : 'ItemSimilarityRecommender_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.ItemSimilarityRecommender)
  })
_sym_db.RegisterMessage(ItemSimilarityRecommender)
_sym_db.RegisterMessage(ItemSimilarityRecommender.ConnectedItem)
_sym_db.RegisterMessage(ItemSimilarityRecommender.SimilarItems)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _ITEMSIMILARITYRECOMMENDER._serialized_start=80
  _ITEMSIMILARITYRECOMMENDER._serialized_end=770
  _ITEMSIMILARITYRECOMMENDER_CONNECTEDITEM._serialized_start=564
  _ITEMSIMILARITYRECOMMENDER_CONNECTEDITEM._serialized_end=620
  _ITEMSIMILARITYRECOMMENDER_SIMILARITEMS._serialized_start=623
  _ITEMSIMILARITYRECOMMENDER_SIMILARITEMS._serialized_end=770
# @@protoc_insertion_point(module_scope)
