# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NearestNeighbors.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import DataStructures_pb2 as DataStructures__pb2
try:
  FeatureTypes__pb2 = DataStructures__pb2.FeatureTypes__pb2
except AttributeError:
  FeatureTypes__pb2 = DataStructures__pb2.FeatureTypes_pb2
from . import Parameters_pb2 as Parameters__pb2
try:
  DataStructures__pb2 = Parameters__pb2.DataStructures__pb2
except AttributeError:
  DataStructures__pb2 = Parameters__pb2.DataStructures_pb2
try:
  FeatureTypes__pb2 = Parameters__pb2.FeatureTypes__pb2
except AttributeError:
  FeatureTypes__pb2 = Parameters__pb2.FeatureTypes_pb2

from .DataStructures_pb2 import *
from .Parameters_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x16NearestNeighbors.proto\x12\x14\x43oreML.Specification\x1a\x14\x44\x61taStructures.proto\x1a\x10Parameters.proto\"\xb6\x04\n\x1bKNearestNeighborsClassifier\x12J\n\x15nearestNeighborsIndex\x18\x01 \x01(\x0b\x32+.CoreML.Specification.NearestNeighborsIndex\x12?\n\x11numberOfNeighbors\x18\x03 \x01(\x0b\x32$.CoreML.Specification.Int64Parameter\x12?\n\x11stringClassLabels\x18\x64 \x01(\x0b\x32\".CoreML.Specification.StringVectorH\x00\x12=\n\x10int64ClassLabels\x18\x65 \x01(\x0b\x32!.CoreML.Specification.Int64VectorH\x00\x12\x1c\n\x12\x64\x65\x66\x61ultStringLabel\x18n \x01(\tH\x01\x12\x1b\n\x11\x64\x65\x66\x61ultInt64Label\x18o \x01(\x03H\x01\x12\x43\n\x10uniformWeighting\x18\xc8\x01 \x01(\x0b\x32&.CoreML.Specification.UniformWeightingH\x02\x12S\n\x18inverseDistanceWeighting\x18\xd2\x01 \x01(\x0b\x32..CoreML.Specification.InverseDistanceWeightingH\x02\x42\r\n\x0b\x43lassLabelsB\x13\n\x11\x44\x65\x66\x61ultClassLabelB\x11\n\x0fWeightingScheme\"\xe2\x02\n\x15NearestNeighborsIndex\x12\x1a\n\x12numberOfDimensions\x18\x01 \x01(\x05\x12\x37\n\x0c\x66loatSamples\x18\x02 \x03(\x0b\x32!.CoreML.Specification.FloatVector\x12\x38\n\x0blinearIndex\x18\x64 \x01(\x0b\x32!.CoreML.Specification.LinearIndexH\x00\x12\x44\n\x11singleKdTreeIndex\x18n \x01(\x0b\x32\'.CoreML.Specification.SingleKdTreeIndexH\x00\x12S\n\x18squaredEuclideanDistance\x18\xc8\x01 \x01(\x0b\x32..CoreML.Specification.SquaredEuclideanDistanceH\x01\x42\x0b\n\tIndexTypeB\x12\n\x10\x44istanceFunction\"\x12\n\x10UniformWeighting\"\x1a\n\x18InverseDistanceWeighting\"\r\n\x0bLinearIndex\"%\n\x11SingleKdTreeIndex\x12\x10\n\x08leafSize\x18\x01 \x01(\x05\"\x1a\n\x18SquaredEuclideanDistanceB\x02H\x03P\x00P\x01\x62\x06proto3')



_KNEARESTNEIGHBORSCLASSIFIER = DESCRIPTOR.message_types_by_name['KNearestNeighborsClassifier']
_NEARESTNEIGHBORSINDEX = DESCRIPTOR.message_types_by_name['NearestNeighborsIndex']
_UNIFORMWEIGHTING = DESCRIPTOR.message_types_by_name['UniformWeighting']
_INVERSEDISTANCEWEIGHTING = DESCRIPTOR.message_types_by_name['InverseDistanceWeighting']
_LINEARINDEX = DESCRIPTOR.message_types_by_name['LinearIndex']
_SINGLEKDTREEINDEX = DESCRIPTOR.message_types_by_name['SingleKdTreeIndex']
_SQUAREDEUCLIDEANDISTANCE = DESCRIPTOR.message_types_by_name['SquaredEuclideanDistance']
KNearestNeighborsClassifier = _reflection.GeneratedProtocolMessageType('KNearestNeighborsClassifier', (_message.Message,), {
  'DESCRIPTOR' : _KNEARESTNEIGHBORSCLASSIFIER,
  '__module__' : 'NearestNeighbors_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.KNearestNeighborsClassifier)
  })
_sym_db.RegisterMessage(KNearestNeighborsClassifier)

NearestNeighborsIndex = _reflection.GeneratedProtocolMessageType('NearestNeighborsIndex', (_message.Message,), {
  'DESCRIPTOR' : _NEARESTNEIGHBORSINDEX,
  '__module__' : 'NearestNeighbors_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.NearestNeighborsIndex)
  })
_sym_db.RegisterMessage(NearestNeighborsIndex)

UniformWeighting = _reflection.GeneratedProtocolMessageType('UniformWeighting', (_message.Message,), {
  'DESCRIPTOR' : _UNIFORMWEIGHTING,
  '__module__' : 'NearestNeighbors_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.UniformWeighting)
  })
_sym_db.RegisterMessage(UniformWeighting)

InverseDistanceWeighting = _reflection.GeneratedProtocolMessageType('InverseDistanceWeighting', (_message.Message,), {
  'DESCRIPTOR' : _INVERSEDISTANCEWEIGHTING,
  '__module__' : 'NearestNeighbors_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.InverseDistanceWeighting)
  })
_sym_db.RegisterMessage(InverseDistanceWeighting)

LinearIndex = _reflection.GeneratedProtocolMessageType('LinearIndex', (_message.Message,), {
  'DESCRIPTOR' : _LINEARINDEX,
  '__module__' : 'NearestNeighbors_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.LinearIndex)
  })
_sym_db.RegisterMessage(LinearIndex)

SingleKdTreeIndex = _reflection.GeneratedProtocolMessageType('SingleKdTreeIndex', (_message.Message,), {
  'DESCRIPTOR' : _SINGLEKDTREEINDEX,
  '__module__' : 'NearestNeighbors_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.SingleKdTreeIndex)
  })
_sym_db.RegisterMessage(SingleKdTreeIndex)

SquaredEuclideanDistance = _reflection.GeneratedProtocolMessageType('SquaredEuclideanDistance', (_message.Message,), {
  'DESCRIPTOR' : _SQUAREDEUCLIDEANDISTANCE,
  '__module__' : 'NearestNeighbors_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.SquaredEuclideanDistance)
  })
_sym_db.RegisterMessage(SquaredEuclideanDistance)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _KNEARESTNEIGHBORSCLASSIFIER._serialized_start=89
  _KNEARESTNEIGHBORSCLASSIFIER._serialized_end=655
  _NEARESTNEIGHBORSINDEX._serialized_start=658
  _NEARESTNEIGHBORSINDEX._serialized_end=1012
  _UNIFORMWEIGHTING._serialized_start=1014
  _UNIFORMWEIGHTING._serialized_end=1032
  _INVERSEDISTANCEWEIGHTING._serialized_start=1034
  _INVERSEDISTANCEWEIGHTING._serialized_end=1060
  _LINEARINDEX._serialized_start=1062
  _LINEARINDEX._serialized_end=1075
  _SINGLEKDTREEINDEX._serialized_start=1077
  _SINGLEKDTREEINDEX._serialized_end=1114
  _SQUAREDEUCLIDEANDISTANCE._serialized_start=1116
  _SQUAREDEUCLIDEANDISTANCE._serialized_end=1142
# @@protoc_insertion_point(module_scope)
