# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: NonMaximumSuppression.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import DataStructures_pb2 as DataStructures__pb2
try:
  FeatureTypes__pb2 = DataStructures__pb2.FeatureTypes__pb2
except AttributeError:
  FeatureTypes__pb2 = DataStructures__pb2.FeatureTypes_pb2

from .DataStructures_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1bNonMaximumSuppression.proto\x12\x14\x43oreML.Specification\x1a\x14\x44\x61taStructures.proto\"\xc0\x04\n\x15NonMaximumSuppression\x12\x46\n\x07pickTop\x18\x01 \x01(\x0b\x32\x33.CoreML.Specification.NonMaximumSuppression.PickTopH\x00\x12?\n\x11stringClassLabels\x18\x64 \x01(\x0b\x32\".CoreML.Specification.StringVectorH\x01\x12=\n\x10int64ClassLabels\x18\x65 \x01(\x0b\x32!.CoreML.Specification.Int64VectorH\x01\x12\x14\n\x0ciouThreshold\x18n \x01(\x01\x12\x1b\n\x13\x63onfidenceThreshold\x18o \x01(\x01\x12#\n\x1a\x63onfidenceInputFeatureName\x18\xc8\x01 \x01(\t\x12$\n\x1b\x63oordinatesInputFeatureName\x18\xc9\x01 \x01(\t\x12%\n\x1ciouThresholdInputFeatureName\x18\xca\x01 \x01(\t\x12,\n#confidenceThresholdInputFeatureName\x18\xcb\x01 \x01(\t\x12$\n\x1b\x63onfidenceOutputFeatureName\x18\xd2\x01 \x01(\t\x12%\n\x1c\x63oordinatesOutputFeatureName\x18\xd3\x01 \x01(\t\x1a\x1b\n\x07PickTop\x12\x10\n\x08perClass\x18\x01 \x01(\x08\x42\x13\n\x11SuppressionMethodB\r\n\x0b\x43lassLabelsB\x02H\x03P\x00\x62\x06proto3')



_NONMAXIMUMSUPPRESSION = DESCRIPTOR.message_types_by_name['NonMaximumSuppression']
_NONMAXIMUMSUPPRESSION_PICKTOP = _NONMAXIMUMSUPPRESSION.nested_types_by_name['PickTop']
NonMaximumSuppression = _reflection.GeneratedProtocolMessageType('NonMaximumSuppression', (_message.Message,), {

  'PickTop' : _reflection.GeneratedProtocolMessageType('PickTop', (_message.Message,), {
    'DESCRIPTOR' : _NONMAXIMUMSUPPRESSION_PICKTOP,
    '__module__' : 'NonMaximumSuppression_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.NonMaximumSuppression.PickTop)
    })
  ,
  'DESCRIPTOR' : _NONMAXIMUMSUPPRESSION,
  '__module__' : 'NonMaximumSuppression_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.NonMaximumSuppression)
  })
_sym_db.RegisterMessage(NonMaximumSuppression)
_sym_db.RegisterMessage(NonMaximumSuppression.PickTop)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _NONMAXIMUMSUPPRESSION._serialized_start=76
  _NONMAXIMUMSUPPRESSION._serialized_end=652
  _NONMAXIMUMSUPPRESSION_PICKTOP._serialized_start=589
  _NONMAXIMUMSUPPRESSION_PICKTOP._serialized_end=616
# @@protoc_insertion_point(module_scope)
