# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: Scaler.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cScaler.proto\x12\x14\x43oreML.Specification\"0\n\x06Scaler\x12\x12\n\nshiftValue\x18\x01 \x03(\x01\x12\x12\n\nscaleValue\x18\x02 \x03(\x01\x42\x02H\x03\x62\x06proto3')



_SCALER = DESCRIPTOR.message_types_by_name['Scaler']
Scaler = _reflection.GeneratedProtocolMessageType('Scaler', (_message.Message,), {
  'DESCRIPTOR' : _SCALER,
  '__module__' : 'Scaler_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.Scaler)
  })
_sym_db.RegisterMessage(Scaler)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _SCALER._serialized_start=38
  _SCALER._serialized_end=86
# @@protoc_insertion_point(module_scope)
