# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: SoundAnalysisPreprocessing.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n SoundAnalysisPreprocessing.proto\x12!CoreML.Specification.CoreMLModels\"\xa0\x01\n\x1aSoundAnalysisPreprocessing\x12V\n\x06vggish\x18\x14 \x01(\x0b\x32\x44.CoreML.Specification.CoreMLModels.SoundAnalysisPreprocessing.VggishH\x00\x1a\x08\n\x06VggishB \n\x1eSoundAnalysisPreprocessingTypeB\x02H\x03\x62\x06proto3')



_SOUNDANALYSISPREPROCESSING = DESCRIPTOR.message_types_by_name['SoundAnalysisPreprocessing']
_SOUNDANALYSISPREPROCESSING_VGGISH = _SOUNDANALYSISPREPROCESSING.nested_types_by_name['Vggish']
SoundAnalysisPreprocessing = _reflection.GeneratedProtocolMessageType('SoundAnalysisPreprocessing', (_message.Message,), {

  'Vggish' : _reflection.GeneratedProtocolMessageType('Vggish', (_message.Message,), {
    'DESCRIPTOR' : _SOUNDANALYSISPREPROCESSING_VGGISH,
    '__module__' : 'SoundAnalysisPreprocessing_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.CoreMLModels.SoundAnalysisPreprocessing.Vggish)
    })
  ,
  'DESCRIPTOR' : _SOUNDANALYSISPREPROCESSING,
  '__module__' : 'SoundAnalysisPreprocessing_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.CoreMLModels.SoundAnalysisPreprocessing)
  })
_sym_db.RegisterMessage(SoundAnalysisPreprocessing)
_sym_db.RegisterMessage(SoundAnalysisPreprocessing.Vggish)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _SOUNDANALYSISPREPROCESSING._serialized_start=72
  _SOUNDANALYSISPREPROCESSING._serialized_end=232
  _SOUNDANALYSISPREPROCESSING_VGGISH._serialized_start=190
  _SOUNDANALYSISPREPROCESSING_VGGISH._serialized_end=198
# @@protoc_insertion_point(module_scope)
