# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: VisionFeaturePrint.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x18VisionFeaturePrint.proto\x12!CoreML.Specification.CoreMLModels\"\xc9\x04\n\x12VisionFeaturePrint\x12L\n\x05scene\x18\x14 \x01(\x0b\x32;.CoreML.Specification.CoreMLModels.VisionFeaturePrint.SceneH\x00\x12P\n\x07objects\x18\x15 \x01(\x0b\x32=.CoreML.Specification.CoreMLModels.VisionFeaturePrint.ObjectsH\x00\x1a\xb7\x01\n\x05Scene\x12Y\n\x07version\x18\x01 \x01(\x0e\x32H.CoreML.Specification.CoreMLModels.VisionFeaturePrint.Scene.SceneVersion\"S\n\x0cSceneVersion\x12\x19\n\x15SCENE_VERSION_INVALID\x10\x00\x12\x13\n\x0fSCENE_VERSION_1\x10\x01\x12\x13\n\x0fSCENE_VERSION_2\x10\x02\x1a\xbe\x01\n\x07Objects\x12]\n\x07version\x18\x01 \x01(\x0e\x32L.CoreML.Specification.CoreMLModels.VisionFeaturePrint.Objects.ObjectsVersion\x12\x0e\n\x06output\x18\x64 \x03(\t\"D\n\x0eObjectsVersion\x12\x1b\n\x17OBJECTS_VERSION_INVALID\x10\x00\x12\x15\n\x11OBJECTS_VERSION_1\x10\x01\x42\x18\n\x16VisionFeaturePrintTypeB\x02H\x03\x62\x06proto3')



_VISIONFEATUREPRINT = DESCRIPTOR.message_types_by_name['VisionFeaturePrint']
_VISIONFEATUREPRINT_SCENE = _VISIONFEATUREPRINT.nested_types_by_name['Scene']
_VISIONFEATUREPRINT_OBJECTS = _VISIONFEATUREPRINT.nested_types_by_name['Objects']
_VISIONFEATUREPRINT_SCENE_SCENEVERSION = _VISIONFEATUREPRINT_SCENE.enum_types_by_name['SceneVersion']
_VISIONFEATUREPRINT_OBJECTS_OBJECTSVERSION = _VISIONFEATUREPRINT_OBJECTS.enum_types_by_name['ObjectsVersion']
VisionFeaturePrint = _reflection.GeneratedProtocolMessageType('VisionFeaturePrint', (_message.Message,), {

  'Scene' : _reflection.GeneratedProtocolMessageType('Scene', (_message.Message,), {
    'DESCRIPTOR' : _VISIONFEATUREPRINT_SCENE,
    '__module__' : 'VisionFeaturePrint_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.CoreMLModels.VisionFeaturePrint.Scene)
    })
  ,

  'Objects' : _reflection.GeneratedProtocolMessageType('Objects', (_message.Message,), {
    'DESCRIPTOR' : _VISIONFEATUREPRINT_OBJECTS,
    '__module__' : 'VisionFeaturePrint_pb2'
    # @@protoc_insertion_point(class_scope:CoreML.Specification.CoreMLModels.VisionFeaturePrint.Objects)
    })
  ,
  'DESCRIPTOR' : _VISIONFEATUREPRINT,
  '__module__' : 'VisionFeaturePrint_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.CoreMLModels.VisionFeaturePrint)
  })
_sym_db.RegisterMessage(VisionFeaturePrint)
_sym_db.RegisterMessage(VisionFeaturePrint.Scene)
_sym_db.RegisterMessage(VisionFeaturePrint.Objects)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _VISIONFEATUREPRINT._serialized_start=64
  _VISIONFEATUREPRINT._serialized_end=649
  _VISIONFEATUREPRINT_SCENE._serialized_start=247
  _VISIONFEATUREPRINT_SCENE._serialized_end=430
  _VISIONFEATUREPRINT_SCENE_SCENEVERSION._serialized_start=347
  _VISIONFEATUREPRINT_SCENE_SCENEVERSION._serialized_end=430
  _VISIONFEATUREPRINT_OBJECTS._serialized_start=433
  _VISIONFEATUREPRINT_OBJECTS._serialized_end=623
  _VISIONFEATUREPRINT_OBJECTS_OBJECTSVERSION._serialized_start=555
  _VISIONFEATUREPRINT_OBJECTS_OBJECTSVERSION._serialized_end=623
# @@protoc_insertion_point(module_scope)
