# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: WordEmbedding.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from . import DataStructures_pb2 as DataStructures__pb2
try:
  FeatureTypes__pb2 = DataStructures__pb2.FeatureTypes__pb2
except AttributeError:
  FeatureTypes__pb2 = DataStructures__pb2.FeatureTypes_pb2

from .DataStructures_pb2 import *

DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13WordEmbedding.proto\x12!CoreML.Specification.CoreMLModels\x1a\x14\x44\x61taStructures.proto\"O\n\rWordEmbedding\x12\x10\n\x08revision\x18\x01 \x01(\r\x12\x10\n\x08language\x18\n \x01(\t\x12\x1a\n\x12modelParameterData\x18\x64 \x01(\x0c\x42\x02H\x03P\x00\x62\x06proto3')



_WORDEMBEDDING = DESCRIPTOR.message_types_by_name['WordEmbedding']
WordEmbedding = _reflection.GeneratedProtocolMessageType('WordEmbedding', (_message.Message,), {
  'DESCRIPTOR' : _WORDEMBEDDING,
  '__module__' : 'WordEmbedding_pb2'
  # @@protoc_insertion_point(class_scope:CoreML.Specification.CoreMLModels.WordEmbedding)
  })
_sym_db.RegisterMessage(WordEmbedding)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'H\003'
  _WORDEMBEDDING._serialized_start=80
  _WORDEMBEDDING._serialized_end=159
# @@protoc_insertion_point(module_scope)
